language: ruby
rvm:
- 2.5.1
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - rackup
  - sleep 3
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: OI2g6n64ie+y/tiSLlH6p3J0GeRQVP3wq++vZoEF8cV9Iae+9SfVj7IvCcjEXw3jEtniwvb7znvqxcBY3nv+0JAM7yroJjhybYSb5DJaDFKfS9zYrXZPFCsDw3KH49xMq7zp/BrT5tMB15nD5IrsV4oTkrCaqheXumzgOnLxwGh5OPJZZfVaKcxjzL82/xeVBQ3MFCQHuQA3sxbChYuy3eBZyXgJ0XqHh6cf68lrU/lBKeJoPEcudFrGyP/Wb9bbZA5UuVv5cJByIXDgXGJD/ncVv9NdVe0fMcjH7YQNrBo3lWyEa9Ujs9AV7f5Hyc0Gx6rQBggAKSm1sUlcGBU/oVATpr97IZ8NQJuaWusgeo6eBb7V1OXBJUT6QY5jbvKHlkGWpfymMDAlZ+2ZDKvuoI84BRmxI7iV3huxhuuGtlGpdFlBOSLZUZ1WFyffbR/r3DeTRZl3THu9irdpIgdPu1AS55n7wUqDBNw3tThl4nYtrHqj+vr4VOypbCgp/2Wt2hTVcWJqb1+GgFIUz51Tl16lMV/LTm2W0FgGYaO9flQIbLFrPHts92mCJrSxDJyBMOoaJjDEsxmFgM6Itgwb0w57zEy6QUDGBEvH0RD2HUOj5R3lWixYK2gtHjB0xCr51wZ02/vZiJOhwf+9JMUie1YvC66kXqy95mETSviRAi0=
  app: nakkekakke-ratebeer
  on:
    repo: nakkekakke/ratebeer
